on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: |
          sudo apt-get install -y python3 pipenv

      - uses: actions/checkout@v2

      - run: |
          pipenv install
          pipenv run python test_cookiecutter.py
